/*
  # Inserción de productos

  1. Productos
    - Productos de diferentes categorías
    - Disponibles en múltiples marketplaces para comparación
    - Información completa incluyendo precios, stock, URLs, etc.
*/

-- Productos Electrónica
INSERT INTO productos (
  nombre_producto, 
  marca, 
  modelo, 
  sku, 
  id_categoria, 
  marketplace, 
  id_seller, 
  precio, 
  precio_anterior, 
  moneda, 
  stock_disponible, 
  url_producto, 
  imagen_url, 
  descripcion, 
  fecha_extraccion, 
  activo, 
  fecha_creacion, 
  fecha_actualizacion
)
VALUES 
  (
    'Smart TV Samsung 50 Pulgadas UHD 4K', 
    'Samsung', 
    'UN50AU7000KXZL', 
    'TV-SAM-50-4K-001', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Televisores' LIMIT 1), 
    'Olímpica', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Olimpica Electro' LIMIT 1), 
    1799900, 
    1999900, 
    'COP', 
    25, 
    'https://www.olimpica.com/televisor-samsung-50-pulgadas', 
    'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=500&auto=format&fit=crop', 
    'Smart TV Samsung 50" UHD 4K, procesador Crystal 4K, HDR10+, diseño sin bordes, compatible con asistentes de voz, conectividad Bluetooth', 
    now() - interval '2 days',
    true, 
    now(), 
    now()
  ),
  (
    'Smart TV Samsung 50 Pulgadas UHD 4K', 
    'Samsung', 
    'UN50AU7000KXZL', 
    'TV-SAM-50-4K-001', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Televisores' LIMIT 1), 
    'Mercado Libre', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'MercadoLibre Oficial' LIMIT 1), 
    1849900, 
    1999900, 
    'COP', 
    18, 
    'https://www.mercadolibre.com.co/tv-samsung-50-pulgadas', 
    'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=500&auto=format&fit=crop', 
    'Smart TV Samsung 50" UHD 4K, procesador Crystal 4K, HDR10+, diseño sin bordes, compatible con asistentes de voz, conectividad Bluetooth', 
    now() - interval '1 day',
    true, 
    now(), 
    now()
  ),
  (
    'Smart TV Samsung 50 Pulgadas UHD 4K', 
    'Samsung', 
    'UN50AU7000KXZL', 
    'TV-SAM-50-4K-001', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Televisores' LIMIT 1), 
    'Alkosto', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Alkosto Oficial' LIMIT 1), 
    1899900, 
    2099900, 
    'COP', 
    12, 
    'https://www.alkosto.com/tv-samsung-50-pulgadas', 
    'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=500&auto=format&fit=crop', 
    'Smart TV Samsung 50" UHD 4K, procesador Crystal 4K, HDR10+, diseño sin bordes, compatible con asistentes de voz, conectividad Bluetooth', 
    now() - interval '3 days',
    true, 
    now(), 
    now()
  ),
  (
    'Smartphone Samsung Galaxy A54', 
    'Samsung', 
    'SM-A546E', 
    'CEL-SAM-A54-001', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Celulares' LIMIT 1), 
    'Olímpica', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Olimpica Electro' LIMIT 1), 
    1599900, 
    1699900, 
    'COP', 
    35, 
    'https://www.olimpica.com/smartphone-samsung-galaxy-a54', 
    'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500&auto=format&fit=crop', 
    'Smartphone Samsung Galaxy A54, pantalla Super AMOLED de 6.4", cámara principal de 50MP, procesador Octa-core, batería de 5000mAh, 128GB almacenamiento', 
    now() - interval '5 days',
    true, 
    now(), 
    now()
  ),
  (
    'Smartphone Samsung Galaxy A54', 
    'Samsung', 
    'SM-A546E', 
    'CEL-SAM-A54-001', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Celulares' LIMIT 1), 
    'Falabella', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Falabella CO' LIMIT 1), 
    1649900, 
    1749900, 
    'COP', 
    22, 
    'https://www.falabella.com.co/smartphone-samsung-galaxy-a54', 
    'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500&auto=format&fit=crop', 
    'Smartphone Samsung Galaxy A54, pantalla Super AMOLED de 6.4", cámara principal de 50MP, procesador Octa-core, batería de 5000mAh, 128GB almacenamiento', 
    now() - interval '2 days',
    true, 
    now(), 
    now()
  ),
  (
    'Laptop HP Pavilion 15.6"', 
    'HP', 
    'Pavilion 15-eh1501la', 
    'PC-HP-PAV-15-001', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Computadores' LIMIT 1), 
    'Olímpica', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Olimpica Electro' LIMIT 1), 
    2499900, 
    2699900, 
    'COP', 
    15, 
    'https://www.olimpica.com/laptop-hp-pavilion', 
    'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop', 
    'Laptop HP Pavilion con pantalla de 15.6", procesador AMD Ryzen 5, 8GB RAM, 512GB SSD, Windows 11 Home', 
    now() - interval '7 days',
    true, 
    now(), 
    now()
  ),
  (
    'Laptop HP Pavilion 15.6"', 
    'HP', 
    'Pavilion 15-eh1501la', 
    'PC-HP-PAV-15-001', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Computadores' LIMIT 1), 
    'Éxito', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Éxito.com' LIMIT 1), 
    2599900, 
    2699900, 
    'COP', 
    8, 
    'https://www.exito.com/laptop-hp-pavilion', 
    'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop', 
    'Laptop HP Pavilion con pantalla de 15.6", procesador AMD Ryzen 5, 8GB RAM, 512GB SSD, Windows 11 Home', 
    now() - interval '4 days',
    true, 
    now(), 
    now()
  );

-- Productos Hogar
INSERT INTO productos (
  nombre_producto, 
  marca, 
  modelo, 
  sku, 
  id_categoria, 
  marketplace, 
  id_seller, 
  precio, 
  precio_anterior, 
  moneda, 
  stock_disponible, 
  url_producto, 
  imagen_url, 
  descripcion, 
  fecha_extraccion, 
  activo, 
  fecha_creacion, 
  fecha_actualizacion
)
VALUES 
  (
    'Licuadora Oster Clásica', 
    'Oster', 
    'BLSTMG-B00', 
    'ELEC-OST-LIC-001', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Cocina' LIMIT 1), 
    'Olímpica', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Olimpica Hogar' LIMIT 1), 
    159900, 
    189900, 
    'COP', 
    42, 
    'https://www.olimpica.com/licuadora-oster-clasica', 
    'https://images.unsplash.com/photo-1622480914645-8fa9a4a8ffce?w=500&auto=format&fit=crop', 
    'Licuadora Oster Clásica con vaso de vidrio de 1.5L, 3 velocidades, sistema reversible de cuchillas, 600W de potencia', 
    now() - interval '10 days',
    true, 
    now(), 
    now()
  ),
  (
    'Licuadora Oster Clásica', 
    'Oster', 
    'BLSTMG-B00', 
    'ELEC-OST-LIC-001', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Cocina' LIMIT 1), 
    'Jumbo', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Jumbo Colombia' LIMIT 1), 
    179900, 
    199900, 
    'COP', 
    38, 
    'https://www.tiendasjumbo.co/licuadora-oster-clasica', 
    'https://images.unsplash.com/photo-1622480914645-8fa9a4a8ffce?w=500&auto=format&fit=crop', 
    'Licuadora Oster Clásica con vaso de vidrio de 1.5L, 3 velocidades, sistema reversible de cuchillas, 600W de potencia', 
    now() - interval '6 days',
    true, 
    now(), 
    now()
  ),
  (
    'Juego de Ollas Imusa', 
    'Imusa', 
    'SET 7 PIEZAS', 
    'COC-IMUSA-OLLAS-001', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Cocina' LIMIT 1), 
    'Olímpica', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Olimpica Hogar' LIMIT 1), 
    199900, 
    249900, 
    'COP', 
    28, 
    'https://www.olimpica.com/juego-ollas-imusa', 
    'https://images.unsplash.com/photo-1585837073804-7d3e3799fcfa?w=500&auto=format&fit=crop', 
    'Juego de 7 piezas de ollas Imusa, incluye 3 ollas con tapa, 1 sartén, fabricadas en aluminio con antiadherente', 
    now() - interval '15 days',
    true, 
    now(), 
    now()
  ),
  (
    'Juego de Ollas Imusa', 
    'Imusa', 
    'SET 7 PIEZAS', 
    'COC-IMUSA-OLLAS-001', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Cocina' LIMIT 1), 
    'Mercado Libre', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'MercadoLibre Oficial' LIMIT 1), 
    219900, 
    259900, 
    'COP', 
    32, 
    'https://www.mercadolibre.com.co/juego-ollas-imusa', 
    'https://images.unsplash.com/photo-1585837073804-7d3e3799fcfa?w=500&auto=format&fit=crop', 
    'Juego de 7 piezas de ollas Imusa, incluye 3 ollas con tapa, 1 sartén, fabricadas en aluminio con antiadherente', 
    now() - interval '8 days',
    true, 
    now(), 
    now()
  );

-- Productos Alimentos
INSERT INTO productos (
  nombre_producto, 
  marca, 
  modelo, 
  sku, 
  id_categoria, 
  marketplace, 
  id_seller, 
  precio, 
  precio_anterior, 
  moneda, 
  stock_disponible, 
  url_producto, 
  imagen_url, 
  descripcion, 
  fecha_extraccion, 
  activo, 
  fecha_creacion, 
  fecha_actualizacion
)
VALUES 
  (
    'Arroz Diana Tradicional 5kg', 
    'Diana', 
    'Tradicional', 
    'ALI-ARR-DIA-5K', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Despensa' LIMIT 1), 
    'Olímpica', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Olimpica Oficial' LIMIT 1), 
    24900, 
    27900, 
    'COP', 
    150, 
    'https://www.olimpica.com/arroz-diana-5kg', 
    'https://images.unsplash.com/photo-1568141696911-27459c18fef2?w=500&auto=format&fit=crop', 
    'Arroz Diana Tradicional en presentación de 5kg, grano entero, 100% colombiano', 
    now() - interval '1 day',
    true, 
    now(), 
    now()
  ),
  (
    'Arroz Diana Tradicional 5kg', 
    'Diana', 
    'Tradicional', 
    'ALI-ARR-DIA-5K', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Despensa' LIMIT 1), 
    'Éxito', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Éxito.com' LIMIT 1), 
    26900, 
    28900, 
    'COP', 
    120, 
    'https://www.exito.com/arroz-diana-5kg', 
    'https://images.unsplash.com/photo-1568141696911-27459c18fef2?w=500&auto=format&fit=crop', 
    'Arroz Diana Tradicional en presentación de 5kg, grano entero, 100% colombiano', 
    now() - interval '2 days',
    true, 
    now(), 
    now()
  ),
  (
    'Leche Alpina Entera 6x1.1L', 
    'Alpina', 
    'Entera', 
    'ALI-LEC-ALP-6X1.1', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Lácteos' LIMIT 1), 
    'Olímpica', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Olimpica Oficial' LIMIT 1), 
    29900, 
    32900, 
    'COP', 
    85, 
    'https://www.olimpica.com/leche-alpina-entera-6x1.1L', 
    'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&auto=format&fit=crop', 
    'Pack de 6 bolsas de leche entera Alpina, cada una de 1.1 litros, pasteurizada y homogeneizada', 
    now() - interval '3 days',
    true, 
    now(), 
    now()
  ),
  (
    'Leche Alpina Entera 6x1.1L', 
    'Alpina', 
    'Entera', 
    'ALI-LEC-ALP-6X1.1', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Lácteos' LIMIT 1), 
    'Jumbo', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Jumbo Colombia' LIMIT 1), 
    30900, 
    33900, 
    'COP', 
    65, 
    'https://www.tiendasjumbo.co/leche-alpina-entera-6x1.1L', 
    'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&auto=format&fit=crop', 
    'Pack de 6 bolsas de leche entera Alpina, cada una de 1.1 litros, pasteurizada y homogeneizada', 
    now() - interval '4 days',
    true, 
    now(), 
    now()
  );

-- Productos Bebidas
INSERT INTO productos (
  nombre_producto, 
  marca, 
  modelo, 
  sku, 
  id_categoria, 
  marketplace, 
  id_seller, 
  precio, 
  precio_anterior, 
  moneda, 
  stock_disponible, 
  url_producto, 
  imagen_url, 
  descripcion, 
  fecha_extraccion, 
  activo, 
  fecha_creacion, 
  fecha_actualizacion
)
VALUES 
  (
    'Coca-Cola Original 2.5L x 4', 
    'Coca-Cola', 
    'Original', 
    'BEB-GAS-COCA-4X2.5', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Gaseosas' LIMIT 1), 
    'Olímpica', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Olimpica Oficial' LIMIT 1), 
    32900, 
    36900, 
    'COP', 
    95, 
    'https://www.olimpica.com/coca-cola-2.5L-x4', 
    'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop', 
    'Pack de 4 botellas de Coca-Cola Original 2.5L cada una', 
    now() - interval '2 days',
    true, 
    now(), 
    now()
  ),
  (
    'Coca-Cola Original 2.5L x 4', 
    'Coca-Cola', 
    'Original', 
    'BEB-GAS-COCA-4X2.5', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Gaseosas' LIMIT 1), 
    'Éxito', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Éxito.com' LIMIT 1), 
    34900, 
    37900, 
    'COP', 
    78, 
    'https://www.exito.com/coca-cola-2.5L-x4', 
    'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop', 
    'Pack de 4 botellas de Coca-Cola Original 2.5L cada una', 
    now() - interval '3 days',
    true, 
    now(), 
    now()
  ),
  (
    'Whisky Old Parr 12 años 750ml', 
    'Old Parr', 
    '12 años', 
    'BEB-ALC-OLDPARR-750', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Alcohólicas' LIMIT 1), 
    'Olímpica', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Olimpica Oficial' LIMIT 1), 
    144900, 
    159900, 
    'COP', 
    42, 
    'https://www.olimpica.com/whisky-old-parr-12', 
    'https://images.unsplash.com/photo-1613590759244-177bdd273ab0?w=500&auto=format&fit=crop', 
    'Whisky Old Parr 12 años, botella de 750ml, whisky escocés de mezcla premium', 
    now() - interval '5 days',
    true, 
    now(), 
    now()
  ),
  (
    'Whisky Old Parr 12 años 750ml', 
    'Old Parr', 
    '12 años', 
    'BEB-ALC-OLDPARR-750', 
    (SELECT id_categoria FROM categorias WHERE nombre_categoria = 'Alcohólicas' LIMIT 1), 
    'Falabella', 
    (SELECT id_seller FROM sellers WHERE nombre_seller = 'Falabella CO' LIMIT 1), 
    149900, 
    164900, 
    'COP', 
    36, 
    'https://www.falabella.com.co/whisky-old-parr-12', 
    'https://images.unsplash.com/photo-1613590759244-177bdd273ab0?w=500&auto=format&fit=crop', 
    'Whisky Old Parr 12 años, botella de 750ml, whisky escocés de mezcla premium', 
    now() - interval '6 days',
    true, 
    now(), 
    now()
  );
